services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_EXT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1.5G
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5

  manticore:
    image: manticoresearch/manticore:latest
    container_name: manticore
    ports:
      - "9306:9306"   # MySQL-compatible port
      - "9308:9308"   # HTTP/REST API port
    volumes:
      - ./manticore/data:/var/lib/manticore
      - ./manticore/config:/etc/manticore
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1500M
    environment:
      - MANTICORE_MEMORY_LIMIT=512M  # Limitar el uso de RAM (ajustable)
    restart: unless-stopped

volumes:
  pgdata:
